development:
  facebook:
    app_id: 169525139755906
    app_secret: a39e69a3a05c4faece4d67b2132e38b2
    # ENSURE canvas_url ends in slash! Or invites relying on URL-joining will not work.
    canvas_url: http://apps.facebook.com/anathief-dev/
  app_server:
    listen_host: 0.0.0.0
    connect_host: anagramthief.com
    port: 8123
    siows_url: http://anagramthief.com:8023
  bot_control:
    listen_host: 127.0.0.1
    connect_host: 127.0.0.1
    port: 19617
  internal:
    allowed_hosts:
      - 127.0.0.1
      - 74.207.243.178
    endpoint: http://anagramthief.com:3000/internal
  wordnik:
    api_key: 27961890eaa589134952f98774c03c1212d7ab4f947cf5b07
  token_secret: bb7db48f5c24572bf12b62118995e8ac0609c2d1533468c9641cee185d632e266dea46a5399a8dfa1e8e301c7c62b0558e960fc5dce381917a4823aa40eddb93

production:
  facebook:
    app_id: 168728976502042
    app_secret: fb1ed0a7bca5572803f7fc48889beb50
    # ENSURE canvas_url ends in slash! Or invites relying on URL-joining will not work.
    canvas_url: http://apps.facebook.com/anagramthief/
  app_server:
    listen_host: 0.0.0.0
    connect_host: anagramthief.com
    port: 8124
    siows_url: http://anagramthief.com:8024
  bot_control:
    listen_host: 127.0.0.1
    connect_host: 127.0.0.1
    port: 19618
  internal:
    allowed_hosts:
      - 127.0.0.1
      - 74.207.243.178
    endpoint: http://anagramthief.com/internal
  wordnik:
    api_key: 27961890eaa589134952f98774c03c1212d7ab4f947cf5b07
  token_secret: bb7db48f5c24572bf12b62118995e8ac0609c2d1533468c9641cee185d632e266dea46a5399a8dfa1e8e301c7c62b0558e960fc5dce381917a4823aa40eddb93
