development:
  facebook:
    app_id: 169525139755906
    app_secret: a39e69a3a05c4faece4d67b2132e38b2
    # ENSURE canvas_url ends in slash! Or invites relying on URL-joining will not work.
    canvas_url: http://apps.facebook.com/anathief-dev/
  redis:
    kprefix: anathief-dev
  juggernaut:
    prefix: anathief-dev
  wordnik:
    api_key: 27961890eaa589134952f98774c03c1212d7ab4f947cf5b07

production:
  facebook:
    app_id: 168728976502042
    app_secret: fb1ed0a7bca5572803f7fc48889beb50
    # ENSURE canvas_url ends in slash! Or invites relying on URL-joining will not work.
    canvas_url: http://apps.facebook.com/anagramthief/
  redis:
    kprefix: anagramthief
  juggernaut:
    prefix: anagramthief
  wordnik:
    api_key: 27961890eaa589134952f98774c03c1212d7ab4f947cf5b07
